version: "3.3"
services:
  coredns:
    image: coredns/coredns:latest
    volumes:
    - ./Corefile.conf:/root/Corefile
    - ./io.db:/root/io.db
    - ./com.db:/root/com.db
    ports:
    - 53:53/udp
    - 53:53/tcp
    command: '-conf /root/Corefile'
##################################################
