version: "3.3"
services:

  gitlab:
    image: gitlab/gitlab-ce:latest
    volumes:
    - gitlab-data:/var/opt/gitlab:Z
    - gitlab-log:/var/log/gitlab:Z
    - gitlab-config:/etc/gitlab:Z
    ports:
    - 8001:80
    - 443:443
    - 1022:22
    hostname: 10.12.7.60.8001
    restart: unless-stopped




#####################
volumes:
  gitlab-data:
  gitlab-log:
  gitlab-config:
