version: '2'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    ports:
      - 8001:80
#      - 443:443
#      - 1022:22
    hostname: 193.176.242.153.8001
