version: '2'

services:
  elasticsearch:
    image: elasticsearch:7.5.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  kibana:
    image: kibana:7.5.0
    ports:
      - 5601:5601
